### ISSUE TITLE
Train Code on Custom dataset not working, please could you help

### ISSUE THREAD

**Issue by tejaskhare99** [Normal-case/Gaussian_YoloV3#1]
Hello, 
Thank you for creating the repository with so much detail.
I am trying to train on a custom dataset
number of class = 1
img size = 416
Setting Arguments.. :  Namespace(cfg='config/gaussian_yolov3_default.cfg', checkpoint=None, checkpoint_dir='checkpoints', checkpoint_interval=1000, debug=False, eval_interval=4000, n_cpu=0, tfboard_dir='./log', use_cuda=True, weights_path='weights/darknet53.conv.74')
successfully loaded config file:  {'MODEL': {'TYPE': 'YOLOv3', 'BACKBONE': 'darknet53', 'ANCHORS': [[10, 13], [16, 30], [33, 23], [30, 61], [62, 45], [59, 119], [116, 90], [156, 198], [373, 326]], 'ANCH_MASK': [[6, 7, 8], [3, 4, 5], [0, 1, 2]], 'N_CLASSES': 1, 'GAUSSIAN': True}, 'TRAIN': {'LR': 0.001, 'MOMENTUM': 0.9, 'DECAY': 0.0005, 'BURN_IN': 1000, 'MAXITER': 10, 'STEPS': '(8, 9)', 'BATCHSIZE': 2, 'SUBDIVISION': 2, 'IMGSIZE': 416, 'LOSSTYPE': 'l2', 'IGNORETHRE': 0.7, 'GRADIENT_CLIP': 2000.0}, 'AUGMENTATION': {'RANDRESIZE': True, 'JITTER': 0.3, 'RANDOM_PLACING': True, 'HUE': 0.1, 'SATURATION': 1.5, 'EXPOSURE': 1.5, 'LRFLIP': False, 'RANDOM_DISTORT': True}, 'TEST': {'CONFTHRE': 0.8, 'NMSTHRE': 0.45, 'IMGSIZE': 416}, 'NUM_GPUS': 1}
effective_batch_size = batch_size * iter_size = 2 * 2
Gaussian YOLOv3
Gaussian YOLOv3
Gaussian YOLOv3
loading darknet weights.... weights/darknet53.conv.74
using cuda
using tfboard
loading annotations into memory...
Done (t=0.00s)
creating index...
index created!
loading annotations into memory...
Done (t=0.00s)
creating index...
index created!
evaluating...
Loading and preparing results...
Traceback (most recent call last):
  File "train.py", line 254, in <module>
    main()
  File "train.py", line 164, in main
    ap = evaluator.evaluate(model)
  File "/content/drive/MyDrive/Gaussian_YoloV3/utils/cocoapi_evaluator.py", line 112, in evaluate
    cocoDt = cocoGt.loadRes(tmp)
  File "/usr/local/lib/python3.7/dist-packages/pycocotools/coco.py", line 327, in loadRes
    'Results do not correspond to current coco set'
AssertionError: Results do not correspond to current coco set

Could you please help me with this, thank you

**Comment by Normal-case** [comment]
Hi, Thank you for your interest in my project. I'm sorry that I wrote it hard to use, not a distribution code. I think this problem is occurred when you convert custom datasets to coco datasets format.

If you used 'create_json.py', please check 'custom.txt' file. The file contains the label name so you should change your own custom label name.

Also, please check the three parts below.
1. utils/utils.py coco_label_names, coco_class_ids convert your own data
2. dataset/cocodataset.py line 85. Check img_file directory
3. utils/cocoapi_evaluator.py line 75. Change the number 65 to 1.

**Comment by tejaskhare99** [comment]
> Hi, Thank you for your interest in my project. I'm sorry that I wrote it hard to use, not a distribution code. I think this problem is occurred when you convert custom datasets to coco datasets format.
> 
> If you used 'create_json.py', please check 'custom.txt' file. The file contains the label name so you should change your own custom label name.
> 
> Also, please check the three parts below.
> 
> 1. utils/utils.py coco_label_names, coco_class_ids convert your own data
> 2. dataset/cocodataset.py line 85. Check img_file directory
> 3. utils/cocoapi_evaluator.py line 75. Change the number 65 to 1.

Hello, Thank you for your response, 
In custom.txt, I have only one word which is - my_class_name

For 1. Utils.py, I have coco_label_names = ['my_class_name'], coco_class_ids = [1]
For 2. I am training on google colab and cv2 requires the entire path hence, I am giving the path and I checked that the image is being read.
For 3. Yes I did the change.
What else could I be doing wrong?
Thank you so much for your help

**Comment by tejaskhare99** [comment]
Hi, if I comment out the ap = evaluator.evaluate(model), it's fine I don't want the evaluation results yet,  I get this error in yolo_layer.py

Traceback (most recent call last):
  File "train.py", line 254, in <module>
    main()
  File "train.py", line 185, in main
    loss = model(imgs, targets)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/content/drive/MyDrive/Gaussian_YoloV3/models/yolov3.py", line 155, in forward
    x, *loss_dict = module(x, targets)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/content/drive/MyDrive/Gaussian_YoloV3/models/yolo_layer.py", line 199, in forward
    obj_mask[b, a, j, i] = 1
IndexError: index 1630 is out of bounds for dimension 2 with size 13

here I checked, size of obj_mask is [2,3,13,13] and b, a, i, j are 0, tensor(2), 1630, 3549, respectively.
Is there anywhere else I need to do some changes for my custom data? 
I tried putting coco_class_ids = [0]

**Comment by Normal-case** [comment]
Have you checked 'gaussian_yolov3_default.cfg' file too? You should change N_CLASSES parameters to your own labels number in the file.

If all of this is not a problem, I'm suspicious of the json file. Can you share a part of the file?

And I realized that this project was too old to modify the code. So I will do refactoring this project as soon as possible.

**Comment by tejaskhare99** [comment]
Hi, yes the cfg file has N_CLASSES as 1.
Here is my instances_train2017.json - 

{
    "categories": [
        {
            "id": 1,
            "name": "handgun",
            "supercategory": "RoadSign"
        }
    ],
    "annotations": [
        {
            "area": 34745289437.34784,
            "bbox": [
                78274.56000000001,
                -1065.375999999991,
                224174.08000000002,
                154992.44799999997
            ],
            "category_id": 0,
            "id": 1,
            "image_id": 1,
            "iscrowd": 0,
            "segmentation": [
                [
                    78274.56000000001,
                    -1065.375999999991,
                    302448.64,
                    -1065.375999999991,
                    302448.64,
                    153927.072,
                    78274.56000000001,
                    153927.072
                ]
            ]
        },
        {
            "area": 62568178610.9952,
            "bbox": [
                104232.96,
                63302.51200000001,
                336793.60000000003,
                185776.03199999998
            ],
            "category_id": 0,
            "id": 2,
            "image_id": 2,
            "iscrowd": 0,
            "segmentation": [
                [
                    104232.96,
                    63302.51200000001,
                    441026.56000000006,
                    63302.51200000001,
                    441026.56000000006,
                    249078.544,
                    104232.96,
                    249078.544
                ]
            ]
        },
        {
            "area": 47772637585.06804,
            "bbox": [
                88854.68800000002,
                58486.687999999995,
                293488.832,
                162774.97600000002
            ],
            "category_id": 0,
            "id": 3,
            "image_id": 3,
            "iscrowd": 0,
            "segmentation": [
                [
                    88854.68800000002,
                    58486.687999999995,
                    382343.52,
                    58486.687999999995,
                    382343.52,
                    221261.66400000002,
                    88854.68800000002,
                    221261.66400000002
                ]
            ]
        },
        {
            "area": 72946383480.42241,
            "bbox": [
                -46991.35999999999,
                -66959.36,
                293662.72000000003,
                248401.91999999998
            ],
            "category_id": 0,
            "id": 4,
            "image_id": 41,
            "iscrowd": 0,
            "segmentation": [
                [
                    -46991.35999999999,
                    -66959.36,
                    246671.36000000002,
                    -66959.36,
                    246671.36000000002,
                    181442.56,
                    -46991.35999999999,
                    181442.56
                ]
            ]
        }
    ],
    "images": [
        {
            "filename": "1.jpg",
            "id": "1",
            "width": 416,
            "height": 416
        },
        {
            "filename": "2.jpg",
            "id": "2",
            "width": 416,
            "height": 416
        },
        {
            "filename": "3.jpg",
            "id": "3",
            "width": 416,
            "height": 416
        },
        {
            "filename": "41.jpg",
            "id": "41",
            "width": 416,
            "height": 416
        }
    ]
}

**Comment by Normal-case** [comment]
Oh, I found the problem. Filename must be written in this format.

"000001.jpg", "000002.jpg", "000003.jpg", "000004.jpg", ... "003721.jpg"

If you look at the 86 line of 'cocodataset.py', img_file is {:06}.format(id_).
So please change filename.

**Comment by tejaskhare99** [comment]
Oh thank you so much I will try that.

**Comment by Tejas992021** [comment]
Hi tried changing the name, I am still getting an error - 
Traceback (most recent call last):
  File "train.py", line 254, in <module>
    main()
  File "train.py", line 185, in main
    loss = model(imgs, targets)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/content/drive/MyDrive/Gaussian_YoloV3/models/yolov3.py", line 155, in forward
    x, *loss_dict = module(x, targets)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/content/drive/MyDrive/Gaussian_YoloV3/models/yolo_layer.py", line 199, in forward
    obj_mask[b, a, j, i] = 1
IndexError: index 4437 is out of bounds for dimension 2 with size 13

I am training only for 4 images validating on 2 images just to see if it works for my dataset. I downloaded the dataset from Open Image dataset V6.

**Comment by tejaskhare99** [comment]
Hi, I tried that but still getting an error - 
Traceback (most recent call last):
  File "train.py", line 254, in <module>
    main()
  File "train.py", line 185, in main
    loss = model(imgs, targets)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/content/drive/MyDrive/Gaussian_YoloV3/models/yolov3.py", line 155, in forward
    x, *loss_dict = module(x, targets)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/content/drive/MyDrive/Gaussian_YoloV3/models/yolo_layer.py", line 199, in forward
    obj_mask[b, a, j, i] = 1
IndexError: index 4437 is out of bounds for dimension 2 with size 13

1. My dataset is from Open Image Dataset detection format of 'class name' x, y, w, h where I am changing the class name to index of 0 as it is being added by 1 in create_json.py
2. In utils.py, the coco_label_names = ('background', 'class_name'); coco_class_ids = [1]
3. I also installed the required versions.

**Comment by tejaskhare99** [comment]
Is this correct?

{
    "categories": [
        {
            "id": 1,
            "name": "handgun",
            "supercategory": "Weapon"
        }
    ],
    "annotations": [
        {
            "area": 971179661721.6001,
            "bbox": [
                -216883.19999999995,
                -193152.0,
                1355366.4000000001,
                716544.0
            ],
            "category_id": 1,
            "id": 1,
            "image_id": 4,
            "iscrowd": 0,
            "segmentation": [
                [
                    -216883.19999999995,
                    -193152.0,
                    1138483.2000000002,
                    -193152.0,
                    1138483.2000000002,
                    523391.99999999994,
                    -216883.19999999995,
                    523391.99999999994
                ]
            ]
        },
        {
            "area": 636026240037.8881,
            "bbox": [
                410098.5600000002,
                168711.59999999998,
                1354563.8399999999,
                469543.20000000007
            ],
            "category_id": 1,
            "id": 2,
            "image_id": 3,
            "iscrowd": 0,
            "segmentation": [
                [
                    410098.5600000002,
                    168711.59999999998,
                    1764662.4000000001,
                    168711.59999999998,
                    1764662.4000000001,
                    638254.8,
                    410098.5600000002,
                    638254.8
                ]
            ]
        },
        {
            "area": 833008295116.7999,
            "bbox": [
                481075.2,
                182603.40000000002,
                1554432.0000000002,
                535892.3999999999
            ],
            "category_id": 1,
            "id": 3,
            "image_id": 2,
            "iscrowd": 0,
            "segmentation": [
                [
                    481075.2,
                    182603.40000000002,
                    2035507.2000000002,
                    182603.40000000002,
                    2035507.2000000002,
                    718495.7999999999,
                    481075.2,
                    718495.7999999999
                ]
            ]
        },
        {
            "area": 462585214402.5599,
            "bbox": [
                361267.20000000007,
                -3073.1999999999744,
                1034649.5999999997,
                447093.6
            ],
            "category_id": 1,
            "id": 4,
            "image_id": 1,
            "iscrowd": 0,
            "segmentation": [
                [
                    361267.20000000007,
                    -3073.1999999999744,
                    1395916.7999999998,
                    -3073.1999999999744,
                    1395916.7999999998,
                    444020.4,
                    361267.20000000007,
                    444020.4
                ]
            ]
        }
    ],
    "images": [
        {
            "filename": "000004.jpg",
            "id": 4,
            "width": 1920,
            "height": 1200
        },
        {
            "filename": "000003.jpg",
            "id": 3,
            "width": 1920,
            "height": 1200
        },
        {
            "filename": "000002.jpg",
            "id": 2,
            "width": 1920,
            "height": 1200
        },
        {
            "filename": "000001.jpg",
            "id": 1,
            "width": 1920,
            "height": 1200
        }
    ]
}

**Comment by Normal-case** [comment]
I found another problem. bbox and segmentation value is weird. bbox is [x, y, w, h] but your value is too big or small. this is because open image size is not 1920x1200. So could you check this please?
